.eslintrc.js

@chriswhong I'd like to remove this out of convenience and personal taste, which was influenced mostly by Mike Bostock D3 examples.

Disable space-before-function-paren, prefer-arrow-callback

---

app/components/main-map.js
app/templates/components/main-map.hbs
app/utils/search-pluto-lots.js
tests/unit/utils/search-pluto-lots-test.js

This PR fixes an issue where lots that are highlighted on mouseover would only partially render due to proximity to a tile edge.  
Instead of only taking the [0]th feature when using `queryrenderedfeatures`, all matching features are added to the map source for highlighting (the only situation where queryrenderedfeatures should return more than one feature is in this tile edge scenario)
Additionally, this PR also "unhighlights" the last highlighted lot when the user mouses out of the lots layer.

fix partial lot highlighting

---

app/components/main-map.js
app/controllers/application.js
app/layer-groups/zoning-map-amendments.js
app/layers/selected-lot.js
app/styles/base/_typography.scss
app/templates/lot.hbs
app/templates/zma.hbs

This PR makes zma polygons clickable on the map, rerouting to zma
Also adds a type header on the content panes, so Tax Lots and Zoning Map Amendments can be easily differentiated.
Closes #50

50 add zma route

---

app/components/layer-control-timeline.js

Adds some moment.js handlers to make the date range slider inclusive of whatever months are selected.  (Before it showed months, but the values passed to the SQL query were  day-specific)
Closes #101

Make date ranges inclusive of entire month

---

app/styles/layouts/_l-default.scss
app/styles/modules/_m-search.scss
app/templates/components/layer-palette.hbs
app/templates/components/map-search.hbs

This PR revises the search layout. 
It's currently ridiculously wide: 
Now that the layer palette is wider, it can match that width: 
I've also added a search icon when there are no terms:

new search layout

---

app/components/layer-group.js
app/layer-groups/aerials16.js
app/layer-groups/zd.js
app/templates/components/layer-group.hbs
app/templates/components/main-map.hbs

This PR adds a fixed order to the layergroups in the app, allowing for toggling layergroups on and off and ensuring that they end up in the same place relative to other layergroups.
Layer order is defined by the order that layergroups are listed in `main-map.hbs`.  (The first layergroup in the template will be the top-most on the map, with the aerial rasters being last)
To accomplish this, we added a computed `before` property in `layer-group.js` which walks through all of the layergroups that are higher than the one being rendered.  If the layergroup's bottom-most layer exists in the map style, it uses that layer as the `before` property.  If not, it tried the next highest layergroup.  
If none of the higher layergroups has any layers on the map, it will default to using `waterway-label` …

Add fixed layer order

---

app/layer-groups/digital-tax-map.js
app/layer-groups/index.js
app/templates/components/layer-palette.hbs
app/templates/components/main-map.hbs

This PR adds a raster layer for the digital tax map, which is proxied through [`labs-zola-search-api`](https://github.com/NYCPlanning/labs-zola-search-api/blob/master/utils/doitt-tiles.js) to manipulate the images into fitting into a standard webmercator tile grid.
Minzoom for the source and the layer is 15.

add dtm raster layer

---

app/components/layer-menu-item.js
app/components/layer-palette-accordion.js
app/styles/_settings.scss
app/styles/app.scss
app/styles/base/_typography.scss
app/templates/components/layer-palette-accordion.hbs
app/templates/components/layer-palette.hbs
tests/integration/components/layer-menu-item-test.js

add badge Sass, stub in layer-palette-accordion-title badge

---

app/layer-groups/neighborhood-tabulation-areas.js

Adds a centroids layer to the NTA vector tile for use in label placement,
removes non-nta features from query (parks, cemeteries, etc)

add centroids data, remove non-ntas

---

app/layer-groups/subway.js

This PR adds subway entrances data, icons, and labels to the map, they fade in after zoom level 15.5.

add subway entrances data, add icons and labels

---

app/controllers/application.js
app/styles/modules/_m-layer-palette.scss
app/templates/components/layer-palette.hbs

This PR switches the Zoning Districts layer to use checkboxes instead of power-select for its filters.
Closes #102.

Zoning Districts checkbox filters

---

app/layer-groups/zoning-districts.js

Fade zoning colors out as tax lots fade in, like:

make zoning fill fade out between zoom 15 and 16

---

app/controllers/application.js
app/layer-groups/zoning-map-amendments-pending.js
app/layer-groups/zoning-map-amendments.js
app/sources/supporting-zoning.js
app/sources/zoning-map-amendments.js

This PR 
- adds effective date to the tooltips for zoning map amendments.
- adds tooltips with ZMA name to certified zoning map amendments.
- makes certified zoning map amendments clickable (routing to the zma route)
Based on `cw-map-improvements`, so don't merge until we are clear on the `source` and `layer` refactoring.
Closes #214

214 zma date tooltips

---

app/components/layer-menu-item.js
app/helpers/admin-boundary-styles.js
app/layer-groups/assemblydistricts.js
app/layer-groups/boroughs.js
app/layer-groups/communitydistricts.js
app/layer-groups/neighborhood-tabulation-areas.js
app/layer-groups/nyccouncildistricts.js
app/layer-groups/nysenatedistricts.js
app/styles/modules/_m-layer-palette.scss
app/templates/components/layer-menu-item.hbs

This PR adds custom styling for each admin boundary layer, along with a `.layer-group-legend`. 
Closes #193. 
Edit: Misnamed this branch. It's not for 198. 😬

style admin layers with legend

---

app/services/map-mouseover.js

This PR changes the ordering position of the `highlighted-lot` layer during the mousemovehandler, causing it to be rendered directly above the layer it is highlighting.  (It used to always be "on top", which shaded layers that were rendered above the feature of interest.

move highlight layer on mouseover

---

app/components/map-search.js
app/controllers/application.js
app/layer-groups/zoning-districts.js
app/layers/selected-lot.js
app/routes/zoning-district.js
app/templates/zoning-district.hbs
tests/unit/controllers/application-test.js

This PR:
- Adds logic to leave the map alone when routing to a zoning district via map click
- Make the map fitbounds for the zoning district when routing from a search result
- Adds a "Fit map to all XX districts" button, so the user can see all if they choose.

141 zoning fitbounds

---

app/layer-groups/pluto.js
app/styles/modules/_m-layer-palette.scss
app/templates/components/layer-palette.hbs

This PR changes the "PLUTO (Tax Lots)" layer palette title to just "Tax Lots" and styles the Land Use colors toggle to look like a part of the Tax Lots layer. See from the before/after below how they used to look like separate items.

better tax lot palette

---

app/templates/components/layer-palette.hbs

This PR reduces the number of layer palette accordions, in an attempt to group layer groups (🙃) into better categories. Subways were in a group by themselves. As were Aerials. 
These four layer groups are now in one accordion: 
- Subways
- Building Footprints 
- 3D Buildings 
- 2016 Aerials 
Note: I'm not sure "Basemaps" is the right title. Maybe "Basemaps & Extras"

Fewer Palette Accordions

---

app/routes/application.js

Redirects to about page if no hash is currently in the route. Eventually, a hash is appended, even if there is none in the original route. Closes #225

Redirect if root/no hash

---

app/layer-groups/effective-flood-insurance-rate-2007.js
app/sources/effective-flood-insurance-rate-2007.js
app/templates/lot.hbs

This PR swaps the "Effective Flood Insurance Rate Maps 2007" layer's raster tiles for vector and adds it to the list of intersecting supporting layers in the lot view.

vector 2007 floodplain

---

app/helpers/carto-download-link.js
app/templates/bookmarks.hbs
tests/integration/helpers/carto-download-link-test.js

This PR adds 2 buttons to the bookmarks view: download csv and download shp. These buttons download respective formats for bookmarked _lots_, including all their map data.
This PR also includes a new helper: `{{carto-download-link table identifier ids format}}`. 
`cartoDownloadLink([table = 'some table', identifier = 'column name for ids', ids='array of ids', format = 'optional format / file extension'])`

Add download links for bookmarked lots

---

app/components/main-map.js
app/routes/zoning-district.js
app/services/main-map.js
app/templates/components/main-map.hbs

This PR fixes the incorrect offset when the user clicks  "Fit map to all XX districts" button in the zoning-district detail view.
It moves the fitBoundsOptions computed property from the `main-map` controller to the `mainMap` service so it can be called from anywhere.
Closes #242

fix manual fitbounds offset

---

app/templates/lot.hbs

This adds a disclaimer for the intersecting layers section, closing #393. [Language](https://github.com/NYCPlanning/labs-zola/blob/e0260a9e15edbbc8b08a33d3042f7f4c26243cd0/app/templates/lot.hbs#L55) of tooltip should be edited/confirmed before merge.

Add disclaimer tooltip

---

app/components/main-map.js
app/templates/components/main-map.hbs

This PR adds dynamic measurement units to the measurement tool, upgrading m to km, feet to miles, m² to km², and feet² to mi² when the threshold of 1 unit of the greater type is reached, also changing the numeral template to show 2 decimal places.  (999m advances to 1.00km) or (5279ft advances to 1.00mi)
Also refactors all the logic happening in the `handleMeasurement()` action making it easier to read and maintain.
Closes #419

Measuring Tool Refactor

---

app/components/main-map.js
app/routes/application.js
app/services/main-map.js

This PR addresses the bug where the initial URL hash was being overridden because the app wanted to fitBounds when it first loads.  (Fitbounds on first load was necessary because half of the map is covered by the information pane on large screens, but the full map shows on small screens.
Fixes:
- The initial longitude of the maps center is now a computed property and is based on the same logic that handles the fitBoundsOptions for both conditions of the map.  
- Somewhat related, this PR adds logic to only show the "About" pane if the initial URL has no location hash.  (This effectively shows it on first load, but ensures that a saved URL with a hash actually has the same view when opened as the user who shared it saw.
Closes #423

Fix url hash override bug

---

app/layer-groups/threed-buildings.js
app/templates/components/main-map.hbs

This PR makes the 3d Buildings layer more opaque, and also changes the rendering order to make sure it appears above tax lots and zoning districts.  It also darkens the color a bit.  The existing layer was too transparent, causing a lot of sloppy overlap of 3d buildings and other rendered features.

Cw opaque 3d buildings

---

app/layer-groups/commercial-overlays.js

This PR adjusts the symbology of the commercial overlays line layer, making it much more subtle on initial load of the app by reducing the line-width when zoomed out.

simple change to line-width and zoom breaks of co layer

---

app/router.js
app/routes/bbl.js
tests/acceptance/visit-lot-test.js
tests/unit/routes/bbl-test.js

Simple commit that adds a `/bbl` route. Uses already implemented `bbl-demux` to parse bbl and redirect to `/lot` route.
Unit and acceptance tests included.

Add /bbl route

---

app/templates/lot.hbs

This PR restores commercial overlays to the "Zoning District" section of the lot profile, and removes them from the "intersecting layers" section.
Closes #458

remove commercial overlays from intersecting layers section

---

app/components/map-search.js

This PR adds a workaround fix for the bug in #447 where clicking address search results when on a non-index route does not fly the map to the search result.
This fix delays the route change until after the `flyTo()` is complete.
Closes #447, but it's just a workaround and leaves a clumsy UI where the content pane remains visible until after the flyTo animation.  #474 was created as a new bug to get this working correctly in the future.

workaround for flyTo bug on search result click

---

app/controllers/lot.js
app/templates/lot.hbs

This PR adds a computed variable to zero-pad 1-digit zoning map names, only for building the historical zoning map links.
Closes #505

505 zoning map links

---

app/styles/layouts/_l-default.scss

This PR was an attempt at #454. 
It does not close the issue, but resolves part of it. 
- Does: fix the missing map on iOS landscape devices
- Does not: fix the hidden `.close-button` on Safari
I've investigated and documented the close button bug in the issue. As it's a failing of Safari to follow the CSS spec, I'm not sure how to resolve it without changing the design. I may have to move the button out of its parent `.content-area` element, which'll require quite a few changes to the layout CSS.  Let's get this map fix in tho.

Fix missing map on landscape iPad

---

app/styles/layouts/_l-default.scss
app/templates/about.hbs
app/templates/bookmarks.hbs
app/templates/commercial-overlay.hbs
app/templates/data.hbs
app/templates/features.hbs
app/templates/lot.hbs
app/templates/special-purpose-district.hbs
app/templates/special-purpose-subdistricts.hbs
app/templates/zma.hbs
app/templates/zoning-district.hbs

This PR moves the `.close-button` outside of the `.content-area`, since Safari (wrongly) doesn't allow fixed-positioned children to ignore their parent's `overflow:hidden`. This has the downside of adding a bit of whitespace at the top of the content area on smaller screens. 
Closes #454.

Fix close button for Safari

---

app/layer-groups/pluto.js
app/sources/pluto.js
package-lock.json

This PR adds tax lot number labels that appear at zoom 16.5, and are at full opacity at zoom 17.5.
Closes #446

add lot labels to tax lots layergroup

---

app/layer-groups/pluto.js
app/templates/components/layer-palette.hbs

This PR adds a `default` parameter to the `fill-color` on the `pluto-fill` layer. This gives the "Other" land use a specific color, instead of defaulting to the stock Mapbox style (black).

Set a default land use color so "Other" isn't so prominent

---

app/index.html
package.json
yarn.lock

This PR… 
- Upgrades `mapbox-gl` by adding version `^0.45.0` explicitly to dependencies, which prevents iOS scrolling the whole page while the user tries to scroll the map
- Sets `user-scalable=no` in the viewport meta, which prevents iOS unintentionally zooming the app when trying to zoom the map 
Closes #582

Fix iOS Safari scrolling issues

---

app/templates/zma.hbs

-Turns ulurp number on zoning map amendment route into a link that goes to the new zap frontend.  (Depends on this PR to be deployed: https://github.com/NYCPlanning/labs-zap-api/pull/48)
- Removes the existing lucats link from the zoning map amendment route
Closes #578

add zap link for ulurp number

---

app/components/intersecting-layers.js
app/controllers/lot.js
app/templates/components/intersecting-layers.hbs
app/templates/lot.hbs

- Restore intersecting features list, which was not showing due to an incorrectly handled task.  Closes #630
- Fix improperly-named floodplain table intersections, confirm that 2007 and 2015 flood plain intersecting layers correspond with what is being symbolized on the map.  Closes #580
- Spot checked intersecting layers throughout the city, unable to find a situation where intersecting layers does not match what is symbolized on the map. Closes #354
- Restore Special Purpose District Intersection, which was getting a bad response from carto due to composing a SQL query with an undefined geometry.  Closes #629

580 incorrect intersection

---

app/components/main-map.js
app/templates/components/main-map.hbs
package.json

_Do not merge until ember-mapbox-composer has been upgraded to 0.0.6_ via https://github.com/NYCPlanning/ember-mapbox-composer/pull/8
Adds `interactivity` property to labs-layers component, based on drawMode.  Fixes the bug where things were highlighting and the map was responding to clicks during drawing mode.

disable map interactivity when in draw mode

---

app/components/road-view.js
app/templates/components/road-view.hbs
app/templates/lot.hbs
package.json
tests/integration/components/road-view-test.js
yarn.lock

This PR adds lazy loading for the network intensive cyclomedia viewer.
- Adds `ember-in-viewport` mixin which triggers an event when a component enters the viewport
- Adds `road-view` component instead of hard-coding the cyclomedia iframe in the `lot` template
- Switching lots generates only 13 network requests instead of 214! (as long as the iframe is out of view)
Closes #644

644 lazy load

---

app/components/main-map.js
app/components/tooltip-renderer.js
ember-cli-build.js
package.json

Removes mustache and uses ember's internal templating; lazy loads turf assets except bbox

Remove mustache; lazy load some turf assets

---

app/components/main-map.js
app/controllers/application.js
app/controllers/zoning-district.js
app/mixins/update-selection.js
app/models/commercial-overlay.js
app/models/special-purpose-district.js
app/models/special-purpose-subdistrict.js
app/models/zoning-district.js
app/routes/application.js
app/routes/bookmarks.js
app/routes/commercial-overlay.js
app/routes/lot.js
app/routes/special-purpose-district.js
app/routes/special-purpose-subdistricts.js
app/routes/zma.js
app/routes/zoning-district.js
app/services/main-map.js
app/templates/components/main-map.hbs
app/templates/special-purpose-subdistricts.hbs
app/templates/zoning-district.hbs
ember-cli-build.js
package.json
yarn.lock

This PR closes #680 by eliminating the `fitBounds` animation when the routing intent is something other than application, about, or index, reducing the average lot profile view size to around 2mb (down from 6mb). 
This PR also refactors the way fitBounds is handled. Instead of an awkward template-based approach, we explicitly call `fitBounds` from the map instance. We handle asynchrony by using tasks that wait for the mapInstance to be available. 
Please pay special attention to these routes:
Manual test them by:
1. Turning on their respective layer if needed.
2. Navigating to that layer by clicking on it from the map.
3. Checking that there's no missing content (telltale signs include lone `|`s, templates with only generic text).
4. Reload the route and make sure that it fits the map to …

680 init map to lot

---

app/components/layer-palette.js
app/components/tooltip-renderer.js
app/controllers/application.js
app/routes/application.js
app/templates/components/tooltip-renderer.hbs
package.json
yarn.lock

This PR updates to latest version of mapbox-composer, which includes a number of fixes:
- tile stitching for highlights
- aggregate layer group state service
- some bug fixes
@hannahkates there are still some bugs mainly with *inbound query params setting up map toggles correctly*, specifically with layer group "substate" (commercial overlays, for example, have several nested filters for types). Everything else seems fairly normal. 
The aerials also doesn't quite work with QPs just yet.
I am not fully comfortable promoting this to master. There needs to be a rewrite of:
1. Grouped controls for layer-group substate
2. layer-group substate should support other properties (filter, for example)
Let me know your thoughts.

Integrate mapbox composer upgrade

---

app/models/lot.js

MapPLUTO v18.1.1 contains different capitalization in the `zonemap` field, so we need to convert to lowercase in order to generate valid links to the zoning map PDFs.

convert zonemap to lowercase

---

app/adapters/zoning-district.js
app/sources/zoning-districts.js
tests/integration/helpers/extract-layer-stops-for-test.js

When updating to use the latest datasets, the zoning_districts table name was accidentally entered as zoning_subdistricts. This caused the route transitions to break when clicking on a zoning district.

fix typo in zoning_districts table name

---

app/adapters/lot.js
app/components/bbl-lookup.js
app/components/intersecting-layers.js
app/sources/pluto.js
app/templates/bookmarks.hbs
config/environment.js
scripts/sitemap.js
tests/integration/helpers/carto-download-link-test.js

This PR:
- Updates MaPLUTO from v18.1.1 to v18.2
- Adds a devlocal environment to test the layers API while running it locally

Update mappluto table name + add devlocal

---

app/components/main-map.js
app/routes/application.js
tests/acceptance/visit-lot-test.js

This PR replaces the default OSM street labels the official street name labels (including street width).  This is the same street label data used in [streets.planning.nyc.gov](https://streets.planning.nyc.gov)
- manually remove `highway_name_other` and `highway_name_motorway`
- add `street-centerlines` layergroup with `visible:true`
Closes #699

hide default street names, add dcp street labels

---

app/models/lot.js
app/templates/lot.hbs

This PR adds housenum and street computed properties (from address -- parsed with regex) to lot model, and exposes HPD resource link in lot profile template. HPD resource link is compose from borocode, housenum, and street values. 
Screen shot shows how the link looks, inserted below ACRIS link
Closes #697

697: Add housenum and street to lot model, expose HPD resource in lot profile template

---

app/adapters/commercial-overlay.js
app/adapters/special-purpose-district.js
app/adapters/special-purpose-subdistrict.js
app/adapters/zma.js
app/adapters/zoning-district.js
app/controllers/lot.js
app/sources/commercial-overlays.js
app/sources/supporting-zoning.js
app/sources/zoning-districts.js
app/sources/zoning-map-amendments.js
app/templates/lot.hbs
tests/integration/helpers/extract-layer-stops-for-test.js
tests/integration/helpers/get-unique-options-for-test.js
yarn.lock

Closes #764 by updating some Carto queries to use new aliased views that have been created on Carto for datasets that have new Jan versions.
More info about the views is available in the layers-api PR description: https://github.com/NYCPlanning/labs-layers-api/pull/106

764: use aliased views for new jan datasets

---

app/controllers/application.js
app/templates/application.hbs
package.json
tests/acceptance/bbl-lookup-test.js
yarn.lock

*Depends on merge and publishing of API changes on `labs-ember-search` (https://github.com/NYCPlanning/labs-ember-search/pull/11)*
This PR adds handling for both block and lot lookups using `labs-bbl-lookup` component (part of `labs-ember-search` addon)
- Uses new API in labs-ember-search 3.0.0
- Handles lot lookup by transitioning to `lot` route
- Handles block lookup by calling `flyTo` on the map
Closes #684

684 block lot lookups

---

app/templates/components/main-map.hbs
package.json
yarn.lock

This PR updates the usage of the labs-layers component from ember-mapbox-composer addon version 0.2.0
Closes #736

Update use of labs-layers component

---

package.json
tests/acceptance/bbl-lookup-test.js
yarn.lock

Closes #658 (NYCPlanning/ember-mapbox-composer#31) by updating composer version which includes handling for “clickable” layer groups

Fix misleading mouse cursor issue

---

app/templates/components/layer-palette.hbs
config/environment.js

This PR bumps`ember-mapbox-composer` to v0.2.1, and restores some lost markup on the aerials toggles that was accidentally reverted.  
Closes #724 *AGAIN*

restore aerials toggles

---

app/styles/layouts/_l-print.scss

This PR adds an attribution to the bottom of the print layout.

Print Attribution

---

app/styles/layouts/_l-print.scss

This PR prevents the SVGs in the print controls buttons from intercepting the component's click event. 
The bug was that… 
When you clicked on a print control button — e.g. the landscape button — a `mut` action on the button changed the attribute and a `click` event on the `print-view-controls` component triggered a window resize for the map. If that click was on the SVG within the button, the action would work fine but the SVG would intercept the click event. So the print layout would change but the map would not resize unless you clicked a part of the button other than the SVG.

prevent SVGs intercepting print controls click event

---

app/components/tooltip-renderer.js
app/routes/application.js
package.json
tests/integration/components/tooltip-renderer-test.js
yarn.lock

Fixes a regression with tooltip templating and addresses #696 by upgrading `ember-mapbox-composer` which includes a better approach to handling hover events for overlapping layers. Needs some review to see if the behavior has improved.
@hannahkates if you can find specific issues maybe GIF them or show me ways to manually test this.
Closes #696 #785 #786 
Thanks!

696 click ordering

---

app/templates/lot.hbs

This PR fixes a typo in the lot content component template that was displaying `lot.overlay1` twice, instead of `lot.overlay1` and `lot.overlay2` from the lot model
Closes #639

639: Fix duplicate display of first commercial overlay in zoning district list

---

app/styles/layouts/_l-print.scss
app/templates/application.hbs
app/templates/components/print-view-controls.hbs

This PR removes the "Content" checkbox in the print settings when there is no content to print (when you're on the index route). It use a "index-active-detector" — which is an invisible Ember `{{link-to}}` component that gets an active state when you're on the index page — and general sibling selectors to adjust styles when you're on the index route. 
Also fixes a couple print layout bugs where the map was aligned to the edge of the paper, without any margin. 
_* This index-active-detector method is used on other apps like Waterfront to determine how tall the map should be on mobile when the layer menu is open/closed._
Closes #789

No-content Printing 

---

app/adapters/lot.js
app/components/intersecting-layers.js
app/sources/effective-flood-insurance-rate-2007.js
app/sources/pluto.js
app/sources/preliminary-flood-insurance-rate.js
app/sources/supporting-zoning.js
app/templates/bookmarks.hbs
app/templates/lot.hbs
public/layer-groups.json
scripts/sitemap.js
tests/integration/helpers/carto-download-link-test.js

This PR updates Carto queries to query from aliased views of the latest dataset version. This reduces data maintenance overhead (now we only need to redefine the view when we get a new data version instead of find/replacing the table name throughout the code base) and makes this app match data view references used in all our other apps.
Related to https://github.com/NYCPlanning/labs-layers-api/pull/124

use-aliased-data

---

app/templates/lot.hbs

Closes #795, making it easier to identify which zoning map a lot is in without needing to open a new tab.

795: add zoning map id to link

---

app/components/layer-palette.js
app/templates/components/layer-palette.hbs
tests/acceptance/navigating-to-qpd-url-breaks-test.js
tests/integration/components/layer-palette-test.js

Note: I added a test (that is skipped for now) for the Reset Map button at the bottom of the layers palette. This button is broken right now (issue #798 ). This test can be used while fixing that bug in another branch.
Closes #849

849: add test for layer-palette

---

app/components/main-map.js
app/components/map-measurement-tools.js
app/services/layer-groups.js
app/services/main-map.js
app/templates/application.hbs
app/templates/components/main-map.hbs
app/templates/components/map-measurement-tools.hbs
ember-cli-build.js
package.json
tests/acceptance/navigating-to-qpd-url-breaks-test.js
tests/acceptance/root-query-params-honored-after-redirect-test.js
tests/helpers/stub-basic-map.js
tests/integration/components/main-map-test.js
tests/integration/components/map-measurement-tools-test.js
yarn.lock

Addresses #805
- This PR fixes a bug where direct, query-param'd links to main root of the app were redirecting to /about _without_ query params. Please review`services/layer-groups.js`
- Tests are added to demonstrate bug and increase coverage in main-map component
- As a rider, this PR splits out the measurement tools part of the map - specifically, that component is called map-measurement-tools. It shouldn't receive a thorough code review as it's largely moving code around. I would like input on the general direction (splitting it out into a component, the name of that component, using contextual params, etc).

Refactor main-map; fix routing bug with redirect

---

app/mixins/update-selection-all-features.js

While search is deactivated for zoning districts, commercial overlays, zoning map amendments, special purpose districts, and special purpose subdistricts, this PR removes the `search` option from a Mixin that determines search vs. click layer interactivity. 
The deactivation of search for these layers was causing clicking on a layer to not transition to the appropriate route--this should remove that error for now. 
This is a quick fix and will be reverted once search is working again. 
Addresses #854

854: QuickFix, remove search as an option from mixin while search is deactivated

---

app/serializers/application.js
app/templates/application.hbs
tests/acceptance/user-can-navigate-away-from-print-via-header-test.js

Addresses #784 by removing the click handler for banner link-to, which was calling currently-broken "reset query params" functionality. 
This also explicitly turns off the print QP when navigating to index.
Includes a test for behavior.
Cleans up the nasty application serializer for 🏕

784 address qp bug with print

---

app/app.js
app/templates/application.hbs
app/templates/commercial-overlay.hbs
app/templates/components/bookmark-button.hbs
app/templates/components/layer-palette.hbs
app/templates/zoning-district.hbs
package.json
tests/acceptance/bookmarks-test.js
tests/acceptance/index-test.js
tests/acceptance/layer-behavior-tests-test.js
tests/acceptance/navigating-to-qpd-url-breaks-test.js
tests/acceptance/query-params-persist-test.js
tests/acceptance/user-can-configure-print-view-test.js
tests/acceptance/visit-lot-test.js
tests/acceptance/visual-diff-routes-test.js
tests/helpers/stub-basic-map.js
yarn.lock

This PR adds a much-needed implementation of tests based on the "layer behavior grid". This test suite will let us move move forward with code improvements.
Note that there are 5 of these tests that are set up as "todo" tests, meaning they fail (in 1 of 8 assertions), but may still be merged as they are behaviors that do not match up with what the behavior grid asks for.
Also, Percy snapshots don't work for the map just yet, and I don't have any plans to do it. Getting Percy to work with the map requires doing additional complex test-environment-specific work. I'd like to find a more general solution.

Add failing behavior grid tests

---

README.md
app/components/main-header.js
app/components/print-view-controls.js
app/controllers/application.js
app/services/print.js
app/templates/application.hbs
app/templates/components/main-header.hbs
app/templates/components/main-map.hbs
app/templates/components/print-view-controls.hbs
tests/integration/components/main-map-test.js
tests/integration/components/print-view-controls-test.js
tests/unit/services/print-test.js

- Moves print concerns out of the application controller and into a print service.
- Hooks up  the `main-map`, `main-header` and `print-view-controls` components to the service.
- Adds unit tests for the service's computed properties to generate print classes.
`app/controllers/application.js` line 52, where the print service replaced original print concerns.
and then `app/services/print.js`.
Since `print-view-controls` component is so tightly coupled to the print service, I'm actually thinking that may be made more explicit if I leave the component parameters on `print-view-controls`. E.g.
```
<PrintViewControls
@print={{print.enabled}}
@printViewOrientation={{print.printViewOrientation}}
@printViewPaperSize={{print.printViewPaperSize}}
@printViewShowMap={{print.printViewShowMap}} …
```

876 componentize print feature concerns

---

app/components/main-map.js
app/routes/application.js
app/services/main-map.js
app/templates/components/main-map.hbs
tests/acceptance/root-query-params-honored-after-redirect-test.js

Closes #805 
Preserves the hash on redirect from application route to about.
Requires changes to service to store hash state.
I could not find a way to correctly pass the hash value in `transitionTo`

805 preserve hash

---

app/serializers/bookmark.js
tests/acceptance/bookmarks-test.js

ZMA model was renamed to zoning-map-amendment. This means that old local storages that _might have had_ a zma bookmarked will fail because their local storage contains references to models of an unrecognized type.
This patch simply converts the old name.

Hotfix legacy model name

---

app/routes/application.js
tests/acceptance/direct-load-lot-disables-zoom-test.js

Reverses a regression where it was zooming when going straight to lot
Closes #885

885 disable lot zoom animation

---

app/components/main-map.js
app/templates/components/main-map.hbs
tests/acceptance/bookmarks-test.js

Closes #894 by fixing a regression with outlining bookmarked lots.
This adds a test for the feature as well.

Re-enables bookmarked lot outlines, incl test

---

app/components/mapbox/load-spinner.js
app/styles/modules/_m-maps.scss
app/templates/components/main-map.hbs
app/templates/components/mapbox/load-spinner.hbs
tests/integration/components/mapbox/load-spinner-test.js

Closes #660 
Adds a load spinner to the top left of the map.
Entry point is main-map.hbs - this PR includes a new component that handles the markup and event binding for loading.
@andycochran curious to hear if you have any options about the position of the load spinner. I tried to make it bottom flush right but because we have the information panel on the right positioned _over_ the map, the spinner is hidden.

Add load spinner in top left of map;

---

app/components/map-resource-search.js
app/services/print.js

This PR renames the "Used Search Bar" event as "Searched by Address" and a null event as an empty string.

930: Clarify Google Analytics event labels

---

app/components/layer-palette.js
app/components/main-map.js
app/helpers/zoom-dependent-label.js
app/services/main-map.js
app/templates/components/layer-palette.hbs
tests/integration/helpers/zoom-dependent-label-test.js

Restores zoom dependent warnings.
Takes advantage of @andycochran 's `activeTooltip` parameter on the `layer-group-toggle` component. 
Created a new helper to either return a null value or the warning label to `activeTooltip`. For a given layer group, the helper returns null when the map zoom is higher than all sublayers' minzoom, otherwise it returns a message about possible missing information.  
Detached the `main-map` service's `zoom` property from the app url hash.

642 restore zoom dependent warning labels

---

app/controllers/application.js
app/styles/modules/_m-maps.scss
app/templates/application.hbs
app/templates/components/main-map.hbs
app/templates/components/mapbox/load-spinner.hbs

This PR moves the map load spinner up in the component hierarchy so that it is visible before the map has even begun drawing in order convey that the map itself is instantiating first.
This became more apparent after pre-rendered content was introduced because the map does not get pre-rendered.
Closes #940

Loading spinner works for all stages of map

---

app/components/road-view.js
app/templates/components/road-view.hbs

Makes the Cyclomedia view in the tax-lot detail page a hyperlink if the user is on a mobile or tablet device.
Should address #455 and closes #936.

Make Cyclomedia a hyperlink

---

app/components/labs-ui/layer-group-toggle.js
app/templates/components/labs-ui/layer-group-toggle.hbs
app/templates/components/main-header.hbs

This PR closes #942 by preventing query-parameter-sensitive markup from being loaded in fastboot.
The reason for doing this is that the initial load can flash the "wrong" state (the default state) if query params are loaded (see canary site for comparison).
This also defaults the site header text to desktop mode in the absence of information about the user agent's screen.

Prevent dynamic-sensitive content

---

app/components/announcement-box.js
app/controllers/application.js
app/styles/layouts/_l-default.scss
app/templates/about.hbs
app/templates/components/announcement-box.hbs
app/templates/components/main-header.hbs
config/environment.js
package.json
yarn.lock

- Moves the AnnouncementBox component to the site header so it's available on all routes
- Uses Ember Tooltips instead of custom action to toggle the announcement (added benefit of clicking anywhere on page to close it)
- Adds `what-input` to prevent `:focus` outline styles showing for non-keyboard navigation
- Adds some temporary overrides for Labs UI and Ember Tooltips (should be remove once [this PR](https://github.com/sir-dunxalot/ember-tooltips/pull/370) has been merged/published)
- Updates the language of the announcement to be more friendly/positive

Refactor & style AnnouncementBox

---

config/environment.js

Addresses #946. Adds link lookup for the Special Bay Street Corridor District.

946: add bay street district link

---

app/components/layer-control-timeline.js
app/templates/components/layer-palette.hbs
tests/integration/components/layer-control-timeline-test.js

This PR does two things:
- It increases the date range of the Zoning Map Amendment slide to include ZMAs from 1977 or later.
- It fixes a bug where this slider would only filter out the layer's fill features, but not its borders. It does this but now applying the same filter on all layers within the given layer-group.

New ZMA data and fix slider to filter both lines and fills

---

app/templates/components/road-view.hbs

Closes #962. Gets rid of conditional logic for providing cyclomedia access as an embedded widget vs. a button that opens in a new tab. Now we only provide the button.

962: only show cyclomedia button, not embed

---

app/index.html
ember-cli-build.js

Assets get fingerprinted with MD5 hash at build time. This means the images will be broken if they are not correctly adjusted.
Closes #922

Excludes the Open Graph tag preview image from asset fingerprinting

---

app/services/main-map.js
app/templates/components/main-map.hbs

This PR limits the max pan and zoom out to the immediate areas surrounding NYC. Closes #298.
Leaves some space to the east to accommodate the side content panel covering part of the map.
A: Max zoom out, most southwest corner:
B: Max zoom out, most northeast corner,
- With content panel open:
- With content panel closed:
Feel free to request any edits!

298: Limit max pan and zoom out on map

---

app/adapters/lot.js

Updating the table slug to point to dcp_mappluto, the table in Carto that is synched via /edm-data-operations.
Addresses [AB#3737](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3737)

Fixes pluto-driven bbl data

---

app/components/layer-palette.js
app/templates/components/layer-palette.hbs

Accommodates the extra request to enable toggling individual flood subcategories. 
Builds off existing pattern used for Commercial Districts and Zoning Districts.
Unfortunately this existing pattern is really poorly designed. It depends on those layer sources to have an `overlay` attribute, and the `layer-palette` component code will apply a global array of filters on `overlay` to every layer. So it depends on the `overlay` attribute values to be unique across layers.
In the corresponding [layers-api PR](https://github.com/NYCPlanning/labs-layers-api/pull/259), the flood layer sources now have an `overlay` virtual attribute that is almost a duplicate of `fld_zone`. The pfirm source makes the A, V, Shaded X values unique by prepending `p_`
**Also** moves away from previous pattern of …

2844 Allow toggling individual flood subcategories

---

app/components/layer-palette.js
app/controllers/application.js
app/templates/application.hbs
app/templates/components/layer-palette.hbs
config/environment.js

Fixes [AB#2844](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2844)
Munged two things in this PR (Dont at me :3):
1. Realized I was wrong in my last PR about the global filter on the `overlay` property. Instead I can create a different filter action for firm and pfirm, aside from commercial overlays. The new filter actions will filter on `fld_zone` specifically. Having separate actions also means I don't need the `p_` prefix in front of pfirm codes. 
Consequently I have a sibling PR in layers api to remove the virtual `overlay` attribute I added to the layer groups for fema_firm and fema_pfirm: https://github.com/NYCPlanning/labs-layers-api/pull/260
2. Figured out how to have subtoggles checked by default when the parent toggle is activated (while …

2844 Toggle flood VAX sublayers by default, refactor floodplain filtering

---

app/templates/components/grouped-checkboxes.hbs
config/environment.js

Fixes additional feedback for [AB#2844](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2844)

2844 Add tooltips to group checkbox

---

package.json
yarn.lock

This PR Updates labs-ember-search to 3.1.5. The previous version had a bug that caused the block lookup to not throw a sql error.
Closes #5901

Update labs-ember-search version to 3.1.5

---

app/adapters/special-purpose-subdistrict.js

This removes an variable "subsub" that does not exist in the current version of the subdistricts table.  Previous version of the table did contain the column, but all values were NULL.
Closes #AB8269

8269 'Special Purpose Subdistricts' data does not show

---

config/environment.js

This PR adds Gowanus to the environment file.  Bug also mentions Jerome Ave, which had been fixed in a previous update.
Closes #AB7514

7514 Zola Issue: Special Districts (2) property search results not displaying info for newly added districts

---

app/services/print.js

Implements logic to fire event tag only when print view is enabled, not every time site loads.
Closes #AB9441

9441 'Print' event sent to Google Analytics on site load

---

config/environment.js
package.json

This PR updates Zola to use the new `geosearch-v2` Search API helper. I also tweaked package.json and environment.js to make it easier to point at staging

Switch to geosearch v2 helper and package.json tweaks

---

app/adapters/lot.js
app/models/map-features/lot.js
app/templates/components/layer-record-views/tax-lot.hbs
tests/acceptance/bookmarks-test.js
tests/acceptance/direct-load-lot-disables-zoom-test.js
tests/acceptance/index-test.js
tests/acceptance/layer-behavior-tests-test.js
tests/acceptance/legacy-redirect-test.js
tests/acceptance/retry-carto-query-test.js
tests/acceptance/visit-lot-test.js
tests/acceptance/visual-diff-routes-test.js
tests/unit/models/lot-test.js

- `app/adapters/lot.js`to add `borocode` to the `LotColumnsSQL` API request.
- `app/models/map-features/lot.js` to use `map_pluto`'s `borocode` instead of the first digit of the `cd` value (in this case, it was incorrectly using 2 for the borough code instead of 1).
- `app/templates/components/layer-record-views/tax-lot.hbs` to use new getter with correct column values
- `tests/unit/models/lot-test.js` to include `borocode` to fix failing test
-  updated failing acceptance tests to include a `properties` object with `borocode`
[AB#10530](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/10530)

updated api request to use  borocode column values

---

app/index.html

This changes the index.html so that Google Analytics is only provided the account id that it needs to store the data if the hostname includes 'zola' and does not include 'preview'.
Closes #AB10753

10753 Disable GA4 by default for development and staging

---

package.json
yarn.lock

This PR upgrades the dependency on labs-ember-search to v3.1.6. This new version of labs-ember-search has the change in [this PR](https://github.com/NYCPlanning/labs-ember-search/pull/46/files) so that we are using the correct boro field name in dof_dtm_block_centroids.

3799 Upgrade labs-ember-search to version with correct boro field.

---

config/environment.js

This PR tweaks environment.js for the geosearch v2 upgrades. Before this change, ENV['labs-search'] was incorrectly getting overwritten entirely in production builds which causes the new geosearch v2 helper to not be used.

Fix environment.js to correctly set ember search config for prod builds

---

config/environment.js
netlify.toml

This PR fixes an issue where our calls to the Carto sql api are still incorrectly querying the `planninglabs` instance in the data-qa environment (https://data-qa--labs-zola.netlify.app/), instead of the `dcpadmin` one. That environment is correctly using `dcpadmin` when getting vector tiles, this change will just get the SQL api calls in sync with that.

11298 fix data qa carto domain

---

app/routes/map-feature/zoning-map-amendment.js
app/templates/components/layer-record-views/zoning-map-amendment.hbs
app/templates/map-feature/zoning-map-amendment.hbs
config/environment.js
mirage/config.js

When viewing a Zoning Map Amendment, the ULURP number links to ZAP Search page for appropriate project.
If the API does not return exactly 1 result, or the network request fails, the text will remain as it was previously.
Closes [AB#12132](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/12132)

12132 Add link to ZAP Search to the ULURP IDs

---

app/adapters/e-designation.js
app/components/main-map.js
app/models/e-designation.js
app/models/map-features/e-designation.js
app/router.js
app/styles/layouts/_l-default.scss
app/templates/components/layer-record-views/e-designation.hbs
app/templates/map-feature/e-designation.hbs

Adds a new info panel for E-Designations displaying new copy and unique feature identifiers such as CEQR, E-Number, and ULURP numbers.
Related to tooltip changes in [this PR](https://github.com/NYCPlanning/labs-layers-api/pull/297) in labs-layers-api.
Closes AB[#11999](https://dev.azure.com/NYCPlanning/ITD/_sprints/taskboard/Open%20Source%20Engineering/ITD/23C?workitem=11999)

11999 – Add E-Designation info panel

---

.github/workflows/main.yml

This PR removes a step from the GH action workflow that ran tests. These tests are failing to run in GH actions since [this PR](https://github.com/NYCPlanning/labs-zola/pull/1059) but they still work locally.

Remove test run from GH action until we get it working with node ugprades

---

app/adapters/e-designation.js
app/components/layer-record-views/e-designation.js
app/components/main-map.js
app/models/e-designation.js
app/serializers/carto-geojson-feature.js
app/serializers/e-designation.js
app/templates/map-feature/e-designation.hbs
package.json
yarn.lock

This PR is a fix for an issue with the new E-Designation panel introduced in #1097 wherein feature information fails to load. One suspected issue is the [carto-geojson-feature](https://github.com/NYCPlanning/labs-zola/blob/master/app/serializers/carto-geojson-feature.js) which seems to be using geometry that the E-Designation point features do not have. This fix is a new serializer for E-Designations.

Fix e-designation panel

---

app/index.html

This PR uses RNG to record a sample of only 25% of sessions so we do not go over our allotted budget.
Closes [AB#13404](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/13404)

13404 Update FS script to sample sessions

---

app/models/map-features/lot.js
tests/unit/models/lot-test.js

This PR updates the links to regular and historical zoning maps that users see when they click on a tax lot to point to the files on the media server that MPE recently migrated them to.

Update links to regular and historical zoning maps to point to OTI media server

---

ember-cli-build.js
package.json
yarn.lock

Addresses [AB#13946](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/13946)
This PR switches out the `sass` package for `sass-embedded`. I came across this while doing Ember 4 upgrades via [this GH Issue](https://github.com/adopted-ember-addons/ember-cli-sass/issues/211). On my machine, this is cutting the SASS portion of the build time down from ~24 seconds to ~3 seconds.

Replace sass with sass-embedded and update ember-cli-build to use it

---

app/templates/components/bookmarks/types/lot.hbs
mirage/config.js
mirage/static-fixtures/layer-groups.js
scripts/sitemap.js
tests/integration/helpers/carto-download-link-test.js

Fixed this by updating Zola to use the "dcp_mappluto" table instead. That should fix this issue and ensure Zola is using the most up to date data.
Closes [AB#13835](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/13835)

13835 404 error when trying to download saved Tax Lots (PLUTO) as: CSV or Shapefile

---

app/components/bookmarks/bookmark-button.js
app/components/bookmarks/types/-default.js
app/components/labs-ui-overrides/layer-group-toggle.js
app/components/layer-palette.js
app/components/layer-record-views/-base.js
app/components/locate-me-mobile.js
app/components/main-map.js
app/components/map-measurement-tools.js
app/components/map-resource-search.js
app/components/print-view-controls.js
app/mixins/track-page.js
config/environment.js
package.json
yarn.lock

This PR adds our self-hosted Matomo Tag Manager to ZoLa
Closes [AB#14192](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/14192)

14192 Add Matomo to ZoLa

---

yarn.lock

This PR updates the version of dcp-ember-metrics to a version which checks to see whether _paq exists before attempting to use it, resolving any issues created by adblockers.
Closes [AB#14350](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/14350)

14350 Updated dcp-ember-metrics

---

app/models/map-features/lot.js

This PR fixes the broken link for C3 and C3A districts.  Was found on BBL Bronx, Block 5606, Lot 40.
Closes [AB#15222](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/15222)

15222 C3A Link

---

app/templates/data.hbs

This PR removes the `Updated in ZoLa: ${updated_at}` from the Data Source information page
[AB#14799](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/14977)

14799 Remove date references in ZoLa Data infomation tab

---

app/components/layer-record-views/tax-lot.js
tests/integration/components/layer-record-views/tax-lot-test.js

This PR updates the digital tax map link from `http://maps.nyc.gov/taxmap/map.htm` to `http://gis.nyc.gov/taxmap/map.htm`
in an effort to avoid a 400 on redirect on Chrome browser when redirected to the DOF hosted tax maps
Closes #1155

1155 Update ZOLA DTM link

---

app/routes/data.js

Fixes bug in /data route where attempt was made to call `.uniqBy` on a plain array.
Originally, we were "degrading" the derived EmberArray to a plain array (`.toArray()`). This used to work because Ember prototype extensions were still a thing. But those are no more.
Originally .toArray may have been used by force of habit or some vestigial reason. 
This change removes the .toArray call and keeps the derived EmberArray proxy which includes the .uniqBy method.

Keep derive EmberArray proxy instead of degrading

---

app/models/map-features/lot.js
tests/unit/models/lot-test.js

This PR updates the digital tax map link from `http://maps.nyc.gov/taxmap/map.htm` to `http://gis.nyc.gov/taxmap/map.htm`
Partially Closes #1155  
- #### TO DO: 
[x] - Merge [PR#1157 ](https://github.com/NYCPlanning/labs-zola/pull/1157) into develop to sync the changes

1159 Updated ZOLA DTM link 

---

app/components/layer-record-views/tax-lot.js
tests/integration/components/layer-record-views/tax-lot-test.js

Updates the Digital Tax Map link to point to DOF's new Property Information Portal and pass the BBL correctly.

Update tax lot panel to point to new DOF Property Information Portal

---

app/components/layer-record-views/tax-lot.js

Update the link to PIP so correctly link to the pages for condo lots.

Update PIP link for condos

---

app/controllers/application.js
app/styles/modules/_m-layer-palette.scss
app/templates/application.hbs
app/templates/components/layer-palette.hbs
config/environment.js
config/icons.js

This removes the "Reset Map Layers" button. It adds a similarly formatted button to the top of the menu on the left side which turns off all map layers. When pressed, until another layer is turned on, the button changes to allow the user to revert back to the previous set of layers.
Completes #1189

Dh4 toggle all layers off

---

app/controllers/application.js

Closes #1198.
- Updates default selected aerial layer to be aerials-2022

Update default selected aerial layer

---

app/templates/components/map-resource-search.hbs
package.json
yarn.lock

This PR updates @nycplanning/ember to use the package with the newly created Zola search history functionality.
To pre-populate your search history, paste the below into the console.
```
window.localStorage["search-history"] = '[{"label":"CHRYSLER BUILDING, New York, NY, USA","bbl":"1012970023","geometry":{"type":"Point","coordinates":[-73.97533,40.751639]},"type":"lot","id":0,"typeTitle":"Search History"},{"label":"EMPIRE STATE BUILDING, New York, NY, USA","bbl":"1008350041","geometry":{"type":"Point","coordinates":[-73.985654,40.748433]},"type":"lot","id":0,"typeTitle":"Search History"},{"label":"STATUE OF LIBERTY, New York, NY, USA","bbl":"1000010101","geometry":{"type":"Point","coordinates":[-74.044535,40.689232]},"type":"lot","id":0,"typeTitle":"Search History"},{"label":"YANKEE …
```

Add Search History

---

app/components/map-measurement-tools.js
app/layers/drawn-feature.js
app/templates/components/main-map.hbs
app/templates/components/map-measurement-tools.hbs

Currently, clicking the distance or area button clears any previously drawn distance/area.  With this PR, you are now able to draw multiple lines or shapes, and able to see the sum of the drawn distances/areas.  The X button continues to clear all drawn shapes and stored measurements.
Completes #1195

Allow Multiple Measurements

---

app/components/main-header.js
app/controllers/bookmarks.js
app/routes/application.js
app/templates/application.hbs
app/templates/bookmarks.hbs
app/templates/components/main-header.hbs

This PR allows users to bookmark the current layers, and access their bookmarked layers in the saved menu.
Completes #1192

Add Bookmarking Sets of Layers

---

app/components/layer-record-views/tax-lot.js
app/components/main-map.js
app/components/print-view-controls.js
app/controllers/application.js
app/styles/layouts/_l-default.scss
app/styles/layouts/_l-print.scss
app/templates/application.hbs

This PR adds a button to the side of the layers menu that allows the user to toggle it between displayed and hidden.
->
Completes #1193

DH3 Hide Sidebar

---

config/environment.js

Switching to using heroku layers api Prod URL directly due to issues with planninglabs.nyc domains

Use heroku layers API URL

---

app/index.html
config/environment.js

This PR updates Matomo to use cloud hosting instead of self-hosted.
Part of [ae-private#36](https://github.com/NYCPlanning/ae-private/issues/36)

Update Matomo to use cloud hosting instead of self-hosted.

---

app/controllers/application.js

This PR fixes an apparent bug in the "Toggle All Map Layers Off" functionality introduced in #1181 that was reported in helpscout ticket 3984. Toggling off all layer groups hides the `street-centerlines` layer group which is what renders the street names and widths
Because there is no corresponding toggle for that layer in the layer palette, the only way the user can get them back is by clicking the "Toggle All Layers Back On" button. This code filters out that layer group so that it isn't hidden. Ideally we wouldn't hard code layer group ids into application code like this but, as things stand, there doesn't seem to be an easy way to distinguish layer groups with toggles in the layer palette from those without.

Add exceptions for street-centerlines layer group to logic for hiding all layers

---

config/environment.js

This PR adds a record to environment.js for the new [Bronx East Tremont Corridor special district](https://www.nyc.gov/site/planning/zoning/districts-tools/special-purpose-districts-bronx.page#ETC).

Add record for East Tremont Corridor special district to environment.js

---

app/components/layer-palette.js
app/templates/components/layer-palette.hbs
app/templates/features.hbs
config/environment.js
public/layer-groups.json

Closes #1229 
Closes #1230 
Closes #1231

Issue 1229 Add Zoning Index Layer to ZOLA

---

app/components/layer-record-views/tax-lot/intersecting-layers-views.js
app/templates/components/layer-record-views/tax-lot/intersecting-layers-views.hbs

This PR addresses an issue where the ZFA intersecting layer for tax lots wasn't hidden behind the feature flag and thus would have gone out in the upcoming release for Zoning Map Index.

Update intersecting layer template to hide ZFA layer behind feature flag

---

.gitignore
app/styles/layouts/_l-default.scss

Closes https://github.com/NYCPlanning/labs-zola/issues/1228
To replicate the bug / test out the PR:
1. Open ZoLa / localhost:4200
2. Switch to mobile view if on desktop
3. Close the new features pop up
4. Click on 'Edit Map Layers'
5. Scroll down and exit the "Welcome to..." panel 
Now you should not be able to scroll back up or down. This PR should fix that.*
* The caveat is, the `overflow` property I removed was initially in place to fix a [mobile scrolling issue](https://github.com/NYCPlanning/labs-zola/pull/401/commits/27af75417b9d907e78a9179f84392f493662025d). So it may be that there are some knock-on effects

Layer palette unreachable on mobile

---

app/controllers/application.js

Closes #1269
Note: although I have made the requested changes, they were unnecessary; the site appears to disregard this value and show 2024 by default, the changes will go into effect as soon as the changes to Layers API are in production.

1269 Update default ortho layer to 2024

---

config/environment.js

Closes https://github.com/NYCPlanning/labs-zola/issues/1288
Fixes the "Learn more" link for Special Atlantic Avenue Mixed Use District by adding it explicitly so that the url can be generated from the tag "AAM"

Add aam to environment.js
