- app/templates/index.hbs
This PR adds a welcome message to the index page (pulled from old ZoLa, w/ tweaks), replacing the "This is the index page" text.
> add welcome message

- app/components/main-map.js
- app/components/map-search.js
- app/controllers/application.js
- app/styles/modules/_m-search.scss
- app/templates/application.hbs
- app/templates/components/main-map.hbs
- app/templates/components/map-search.hbs
- app/utils/search-pluto-lots.js
- tests/integration/components/map-search-test.js
- tests/unit/utils/search-pluto-lots-test.js
De-abstract some things (wrong direction); introduces new methods in map-search, more event handlers for keyboard strokes. main-map now has access to a general routeTo action.
Would like @andycochran's design input on arrow down highlighting. Also, please test numerous addresses to check for strange behavior.
Closes #18
> Arrow down & Enter; FlyTo address result

- app/styles/_settings.scss
- app/styles/app.scss
- app/styles/modules/_m-layer-palette.scss
- app/templates/application.hbs
- app/templates/components/layer-group.hbs
- app/templates/components/layer-menu-item.hbs
- tests/integration/components/layer-group-test.js
- tests/integration/components/layer-menu-item-test.js
This PR adds styles for the `.layers-list` and `.layer-group`, adding a foundation switch to indicate the layer state.
> Layer Palette Stlyes

- app/components/main-map.js
- app/controllers/application.js
- app/layer-groups/aerial-raster.js
- app/layer-groups/commercial-overlays.js
- app/layer-groups/pluto.js
- app/layer-groups/zoning-map-amendments.js
- app/templates/components/main-map.hbs
- blueprints/layer-group/files/app/layer-groups/__layerGroupToken__.js
- blueprints/layer/files/app/layers/__layerToken__.js
> 52 add layers tests

- .circleci/config.yml
- app/components/main-map.js
- app/models/lot.js
- app/templates/components/main-map.hbs
- app/templates/lot.hbs
Two pet features:
1. Adds Community District box to lot details pane, including a link to the new community profiles site!
2.  Adds a dynamic padding to the `fitBoundsOptions` that are used to fly the map to a lot when it is selected.  It takes the lesser of height or width and divides by 2.5
> Cw fitbounds profiles

- app/components/main-map.js
- app/controllers/application.js
- app/layer-groups/commercial-overlays.js
- app/layer-groups/zoning-districts.js
- app/layer-groups/zoning-map-amendments.js
- app/models/zma.js
- app/styles/base/_typography.scss
- app/templates/components/main-map.hbs
- app/templates/lot.hbs
- app/templates/zma.hbs
Updates to map styling:
- Rearrange layer order in sidebar
- Some layers off by default
- General map style tweaks
Updates to content areas:
- Add header-subtext to lot view to show BBL
- Add links to zoning sketch map and LUCATS record for zma view
- Add icons to external links
> Cw map improvements

- app/components/layer-control-timeline.js
- app/components/layer-group.js
- app/controllers/application.js
- app/styles/modules/_m-layer-palette.scss
- app/templates/components/layer-control-timeline.hbs
- app/templates/components/layer-group.hbs
- app/templates/components/main-map.hbs
- package-lock.json
- package.json
- tests/integration/components/layer-control-timeline-test.js
Adds timeline slider along with some component logic for managing SQL changes. There are some commented-out "rough draft" of QP binding, but that still needs to be worked out.
> Timeslider filter

- app/styles/modules/_m-layer-palette.scss
- app/templates/components/main-map.hbs
This PR cleans up the layout of the `ul` elements in the layer palette.
> clean up styles for layer palette ul elements

- app/styles/app.scss
- app/styles/modules/_m-layer-palette.scss
- app/styles/modules/_m-noui.scss
This PR styles the Zoning Map Ammendments' date range slider.
> add noUi style overrides for sliders

- app/adapters/zoning-district.js
- app/components/layer-group.js
- app/components/main-map.js
- app/controllers/application.js
- app/layer-groups/zd.js
- app/layers/highlighted-lot.js
- app/layers/selected-lot.js
- app/models/zoning-district.js
- app/router.js
- app/routes/zoning-district.js
- app/serializers/zoning-district.js
- app/templates/components/layer-palette.hbs
- app/templates/components/main-map.hbs
- app/templates/zoning-district.hbs
- tests/unit/routes/zoning-district-test.js
- tests/unit/routes/zoningdistrict-test.js
This PR adds a route for zoning districts, with a simple link to the relevant DCP page.
It also includes some styling updates for the selected layers and highlight layers.
> 78 zoning district route

- app/components/layer-group.js
- app/components/layer-menu-item.js
- app/components/layer-palette.js
- app/components/switch-toggle.js
- app/controllers/application.js
- app/templates/components/layer-group.hbs
- app/templates/components/layer-menu-item.hbs
- app/templates/components/layer-palette.hbs
- app/templates/components/switch-toggle.hbs
- tests/integration/components/switch-toggle-test.js
> Toggle for layer palette; fixes paint swap

- app/components/info-tooltip.js
- app/components/layer-group.js
- app/components/layer-menu-item.js
- app/components/layer-palette.js
- app/components/main-map.js
- app/services/main-map.js
- app/templates/components/info-tooltip.hbs
- app/templates/components/layer-menu-item.hbs
- app/templates/components/layer-palette.hbs
- app/templates/components/main-map.hbs
> 76 layer warning logic

- app/components/layer-group.js
- app/controllers/application.js
- app/routes/lot.js
- app/routes/zma.js
- app/templates/application.hbs
- app/templates/components/layer-palette.hbs
- app/templates/components/main-map.hbs
- app/templates/components/site-header.hbs
Closes #80 - resets QPs when transition out of lot view
> Bind QPs, reset QPs on transition out of Lot

- app/helpers/admin-boundary-styles.js
- app/layer-groups/assemblydistricts.js
- app/layer-groups/boroughs.js
- app/layer-groups/communitydistricts.js
- app/layer-groups/index.js
- app/layer-groups/nta.js
- app/layer-groups/nyccouncildistricts.js
- app/layer-groups/nysenatedistricts.js
- app/templates/components/layer-palette.hbs
- app/templates/components/main-map.hbs
- package-lock.json
Adds many admin boundary layers with common styling.
- Boroughs
- Community Districts
- Council Districts
- State Senate Districts
- State Assembly Districts
- NTAs
> 94 admin boundaries

- app/components/main-map.js
Adds mapboxGL's built-in scale control with imperial units, closes #157
> add ScaleControl

- app/styles/_settings.scss
- app/styles/layouts/_l-default.scss
- app/templates/components/layer-palette.hbs
This PR removes the layer palette's close button and makes toggle button's text dynamic. 
Closes #148.
> Layer Palette Mobile Open/Close

- app/layers/selected-lot.js
Trying out some style tweaks using `line-dasharray` and `line-cap`
> add dotted line to selected feature layer

- app/components/map-search.js
- app/templates/application.hbs
- app/templates/components/map-search.hbs
Fixes zoning district search results (they were throwing an error on click).  
Also added a custom header and icon for them in the search results list.
> fix zone district search result click, add icon

- app/models/lot.js
- app/styles/base/_typography.scss
- app/templates/lot.hbs
- tests/acceptance/index-test.js
> add PLUTO data to lot view in established hierarchy

- app/styles/base/_typography.scss
- app/templates/lot.hbs
This PR tweaks the layout and styles on the Lot view. Supplements #173, which is already closed but could've been prettier.
> 173 pluto layout

- app/styles/modules/_m-icons.scss
- app/styles/modules/_m-layer-palette.scss
- app/templates/components/layer-palette.hbs
Adds simple circle legend for zoning districts.
> Add simple zoning district legends

- app/components/layer-palette.js
- app/components/map-search.js
- app/styles/_settings.scss
- app/styles/layouts/_l-print.scss
- app/templates/components/bookmark-button.hbs
> add basic print styles

- app/routes/bookmarks.js
- app/templates/bookmarks.hbs
- tests/unit/routes/bookmarks-test.js
This PR adds a close button to the bookmarks route and clears the selected map feature. 
Closes #247. Closes #246.
> 247 closebutton

- app/styles/modules/_m-search.scss
> set max-height, scroll on search results on large screen

- app/layer-groups/zoning-districts.js
This PR makes the Zoning Districts layer's lines and labels darker when zoomed in. Closes #286.
> update zoning districts layer styles

- app/adapters/special-purpose-subdistrict.js
- app/controllers/application.js
- app/controllers/special-purpose-subdistricts.js
- app/layer-groups/special-purpose-subdistricts.js
- app/models/special-purpose-subdistrict.js
- app/router.js
- app/routes/special-purpose-subdistricts.js
- app/sources/supporting-zoning.js
- app/templates/bookmarks.hbs
- app/templates/special-purpose-subdistricts.hbs
- tests/unit/adapters/special-purpose-subdistrict-test.js
- tests/unit/controllers/special-purpose-subdistricts-test.js
- tests/unit/models/special-purpose-subdistrict-test.js
- tests/unit/routes/special-purpose-subdistricts-test.js
> SPSD route, Close #272, Address #218

- app/components/main-map.js
- app/controllers/application.js
> Prevent duplicate pins

- app/templates/lot.hbs
This PR adds an external link to historical district info. Part of #288.
> Hist Dist Link

- app/templates/lot.hbs
This PR adds headings for zoning details an intersecting layers, putting them in two columns.
> 332 lot links subheaders

- app/templates/lot.hbs
- package-lock.json
This PR changes the description text for the flood zones in lot view.
Closes #356
> updated floodplain text description

- app/models/zma.js
This PR set null date value to read as "To be determined".
> set null date to read as to be determined

- app/layer-groups/business-improvement-districts.js
- app/layer-groups/index.js
- app/layer-groups/limited-height-districts.js
- app/sources/supporting-zoning.js
- app/templates/components/layer-palette.hbs
- app/templates/components/main-map.hbs
- blueprints/layer-group/files/app/layer-groups/__layerGroupToken__.js
This PR adds limited height district and BIDs as non-clickable layergroups with tooltips.
Closes #277
> 277 bids limited height

- app/templates/about.hbs
> add email to about, change map to app

- app/styles/layouts/_l-default.scss
> make map slightly shorter on mobile

- app/components/main-map.js
- app/controllers/application.js
- app/services/main-map.js
- app/styles/modules/_m-maps.scss
- app/templates/components/main-map.hbs
This PR… 
- adds button to toggle the draw UI on small, medium screens
- adds an active class to the draw tool currently in use
> collapse draw UI for medium down, add active draw class

- app/styles/layouts/_l-default.scss
> fix horz scroll

- app/adapters/lot.js
- app/index.html
- app/models/lot.js
- app/styles/layouts/_l-default.scss
- app/templates/lot.hbs
- package-lock.json
> Working cyclomedia integration

- app/layer-groups/building-footprints.js
This PR turns the building footprints layergroup on by default
Closes #448
> set building footprints on by default

- app/templates/lot.hbs
This PR changes the lot template to use the acris query-param-enabled URL to pull up the BBL-specific link.
Closes #456
> Use acris query params

- app/templates/lot.hbs
This PR adds e-designations to the list of intersecting layers in lot view.
Closes #512
> add e-des intersect

- app/templates/lot.hbs
This PR allows users to set view of CycloMedia iframe to fullscreen using the built in fullscreen button.
- add `allowfullscreen` attributes to iframe which are widely supported with the primary exception of IE versions < 11
Closes #493
> Feature/493 Cyclomedia Full Screen

- app/styles/base/_typography.scss
> HOTFIX: nix IE's default clear buttons

- app/layer-groups/building-footprints.js
> nix building footprint outlines

- app/layer-groups/appendixj-designated-mdistricts.js
- app/layer-groups/index.js
- app/layer-groups/industrial-business-zones.js
- app/sources/supporting-zoning.js
- app/templates/components/layer-palette.hbs
- app/templates/components/main-map.hbs
This PR
- adds Industrial Business Zones (IBZs) layergroup, Closes #436 
- adds Appendix J (Zoning Text) Designated M-Zones layergroup,  Closes #564
> Add IBZs and Appendix J Designated M-Zones

- app/components/main-map.js
- app/styles/modules/_m-maps.scss
- app/templates/components/main-map.hbs
This PR adds a print button which sends the map style & other meta to Planning Labs' [Print Service](https://map-print.planninglabs.nyc).
> 🖨Print Button

- app/templates/lot.hbs
Add Appendix J Designated M Districts to intersecting layers
Closes #583
> add appendix j to intersecting layers

- app/components/bookmark-button.js
This PR updates the computed property that applies a `saved` class to the bookmark button.
Closes #618
> refactor computed that applies saved class to bookmark button

- app/components/bbl-lookup.js
- app/templates/components/bbl-lookup.hbs
This PR… 
- Makes the BBK Lookup element a `form`, moving the action to the form instead of the button, so that pressing enter in the inputs submits the form — closes #574 
- Validates the BBL Lookup by porting over functions from City Map — closes #479 
- Adds the ability to search by block — closes #502
> Improve BBL Lookup Form

- app/adapters/commercial-overlay.js
- app/adapters/special-purpose-district.js
- app/adapters/special-purpose-subdistrict.js
- app/adapters/zma.js
- app/adapters/zoning-district.js
- app/controllers/lot.js
- app/sources/commercial-overlays.js
- app/sources/supporting-zoning.js
- app/sources/zoning-districts.js
- app/sources/zoning-map-amendments.js
- app/templates/lot.hbs
- package-lock.json
- tests/integration/components/layer-checkbox-test.js
- tests/integration/helpers/extract-layer-stops-for-test.js
- tests/integration/helpers/get-unique-options-for-test.js
This PR swapped out table names to provide the latest Aug 2018 data for the following datasets. The previous table versions are provided in parentheses after each of the new table names:
zoning_districts_v201808 (zoning_districts_v201806)
commercial_overlays_v201808 (commercial_overlays_v201806, commercial_overlays_v201804)
zoning_map_amendments_v201808 (zoning_map_amendments_v201806)
special_purpose_districts_v201808 (special_purpose_districts_v201806)
special_purpose_subdistricts_v201808 (special_purpose_subdistricts_v201806)
sidewalk_cafes_v201808 (sidewalk_cafes_v201806)
limited_height_districts_v201808 (limited_height_districts_v201806)
mandatory_inclusionary_housing_v20180823 (mandatory_inclusionary_housing_v20180628)
e_designations_v20180823 (e_designations_v20180628)
> Data v201808

- app/layer-groups/commercial-overlays.js
- app/layer-groups/e-designations.js
- app/layer-groups/limited-height-districts.js
- app/layer-groups/mandatory-inclusionary-housing.js
- app/layer-groups/sidewalkcafes.js
- app/layer-groups/special-purpose-districts.js
- app/layer-groups/special-purpose-subdistricts.js
- app/layer-groups/zoning-districts.js
- app/layer-groups/zoning-map-amendments.js
This PR updates the dates listed on the data tab for each updated dataset.
> updated dates on data tab

- app/models/layer-group.js
- app/models/source.js
- app/routes/data.js
- app/serializers/source.js
- app/templates/components/layer-palette.hbs
- app/templates/data.hbs
- tests/unit/models/source-test.js
- tests/unit/serializers/source-test.js
- yarn.lock
Gets de-duped source metadata on the the page on the /data route.
> 652 fix source models

- config/environment.js
The staging version of zola now connects to the staging layers-api.
> added staging environment to connect to layer-api-staging

- app/index.html
- ember-cli-build.js
- package.json
- yarn.lock
This PR enables embmer-cli-concat, which bundles all javascript & css into a single file. Improves initial page load.
> Install concatenation

- config/environment.js
Add Google Analytics metric adapters to environment.js in the config
> Add Google Analytics to environment.js

- app/templates/components/layer-palette.hbs
> use correct tooltip for sidewalk cafes

- app/routes/application.js
- app/routes/index.js
- app/templates/about.hbs
- app/templates/application.hbs
- app/templates/components/grouped-checkboxes.hbs
- app/templates/components/layer-palette.hbs
- package.json
- tests/acceptance/navigating-to-qpd-url-breaks-test.js
- tests/acceptance/query-params-persist-test.js
- tests/acceptance/selected-zoning-qps-work-test.js
- tests/helpers/extract-query-params.js
- tests/helpers/refresh.js
- yarn.lock
761 Test behaviors for selected overlays
761 add tests for capturing status quo behavior of QPs
Fix lint
761 failing test
Adds a failing test proving the regression behavior
761 Implement fix; add additional tests
Closes #761 
Closes #762
> 761 Add tests for current working behavior

- app/templates/components/layer-palette.hbs
This PR fixes the ampersands in the Land Use Colors legend. Closes #819.
> 819 - Fix Land Use Colors legend ampersands

- config/environment.js
Disable search sources until we can address reliability problems in search API
> Turn off certain search sources

- app/app.js
- app/models/map-features/lot.js
- app/templates/components/layer-record-views/tax-lot.hbs
- tests/unit/models/lot-test.js
Addresses #881 by fixing broken link regressions.
Entrypoint is models/map-features/lot and tax-lot.hbs
> 881 Fix broken lot links

- config/environment.js
Closes #900 by re-enabling search options.
> Re-enable search options

- app/components/bookmarks/bookmark-button.js
- app/components/bookmarks/types/-default.js
- app/components/is-in-viewport.js
- app/components/labs-ui/layer-group-toggle.js
- app/components/layer-palette.js
- app/components/layer-record-views/-base.js
- app/components/map-measurement-tools.js
- app/components/map-resource-search.js
- app/components/print-view-controls.js
- app/services/print.js
- app/templates/components/bookmarks/types/lot.hbs
- app/templates/components/layer-record-views/tax-lot.hbs
- tests/helpers/stub-basic-map.js
This PR add metrics to the layers control, print, measurement tools, bookmarking, search (bbl, address, and zoning districts) features.
> analytics for layers, print, measurement, bookmarks, external links, cyclomedia, and search

- config/environment.js
- mirage/static-fixtures/layer-groups.js
- public/layer-groups.json
- tests/acceptance/navigating-to-qpd-url-breaks-test.js
Implements user requests for minor text updates. Closes #964. Closes #950.
> 964, 950: text edits BYTES TM and Residence

- app/templates/components/layer-record-views/special-purpose-district.hbs
- app/templates/components/layer-record-views/tax-lot.hbs
- app/templates/components/layer-record-views/zoning-map-amendment.hbs
This PR removes the hardcoded Inwood Rezoning disclaimer.
> nix Inwood disclaimers

- config/environment.js
> Point to heroku search deployment

- mirage/static-fixtures/layer-groups.js
Fixes [AB#2940](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2940).
> Add new tooltip language for special purpose subdistricts

- app/adapters/commercial-overlay.js
- app/adapters/special-purpose-district.js
- app/adapters/special-purpose-subdistrict.js
- app/adapters/zoning-district.js
- app/components/intersecting-layers.js
- app/models/map-features/lot.js
This PR will modify a number of queries to use the most up-to-date tables from EDM.
> Hotfix: Update Carto queries with new edm tables

- app/templates/components/layer-record-views/tax-lot/intersecting-layers-views.hbs
This PR updates the link to Appendix J of the ZR.
Closes #AB5923
> 5923 Link to APPENDIX J not working

- .gitignore
- app/adapters/commercial-overlay.js
- app/adapters/special-purpose-district.js
- app/adapters/special-purpose-subdistrict.js
- app/adapters/zoning-district.js
- app/components/intersecting-layers.js
- app/models/map-features/lot.js
- package.json
- yarn.lock
This PR updates the version of labs-ember-search to a new version that has corrected carto data set names and fixes a bunch of linting violations that found their way into master (and then develop) via some hotfix commits.
> Updating labs-ember-search to version with correct sql query and fixing linting violations

- .gitignore
- config/environment.js
Adds new special purpose districts to the `environment.js`
[AB#10479](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/10479)
> add new special purpose districts

- config/environment.js
remove a space in a special district name
[AB#10479](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/10479)
> 10479 removed a darn space in a special district name

- config/environment.js
This PR merges some changes from develop to master to release the switch to geosearch v2 helper to production
> Merging develop to master to release geosearch v2 upgrade

- .gitignore
- app/templates/components/layer-record-views/zoning-map-amendment.hbs
This PR 
Removes the link to non-functional/removed code at Zap.
Closes 
[AB#11316](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/11316)
> 11316 removed ULURP number link

- app/index.html
This PR adds the Fullstory tag.
Closes [AB#11822](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/11822)
> 11822 Add Fullstory Tagging

- app/templates/components/main-header.hbs
- package.json
- public/layer-groups.json
- yarn.lock
Reverts NYCPlanning/labs-zola#1103
> Revert "Remove unused static file and upgrade labs-ui"

- app/templates/components/layer-record-views/e-designation.hbs
> Update CEQR Access button with correct link

- .netlifyredirects
- app/index.html
This PR merges changes to limit the number of FS sessions we track for Zola to master for prod release.
> Merge FullStory sampling up to master

- app/models/map-features/lot.js
- app/templates/components/layer-record-views/tax-lot.hbs
- mirage/static-fixtures/layer-groups.js
- package.json
- tests/integration/helpers/carto-download-link-test.js
- tests/unit/models/lot-test.js
- yarn.lock
This PR {summarize the PR}
Updates the link to HPD Online and adds a tooltip to the Housing Info label.
Closes #{issue number(s)}
ADO [#14684](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/14347/?workitem=14684)
> Task/14684 – Update HPD link and add tooltip to Housing Info label

- app/styles/layouts/_l-default.scss
- app/templates/components/main-header.hbs
Add banner linking to user interview signup form.
> Add banner linking to user interview signup form.

- app/styles/layouts/_l-default.scss
> 1164 modified css to adjust the position of the close button container

- app/styles/layouts/_l-default.scss
- app/templates/components/main-header.hbs
Removing the user interview sign up banner we recently added
> Remove signup banner and scss

- app/templates/components/layer-palette.hbs
- config/environment.js
- mirage/static-fixtures/layer-groups.js
- public/layer-groups.json
- tests/acceptance/layer-behavior-tests-test.js
> Remove sidewalk-cafes layer-group and references

- app/components/layer-record-views/tax-lot.js
- app/templates/components/layer-palette.hbs
- config/environment.js
- mirage/static-fixtures/layer-groups.js
- public/layer-groups.json
- tests/acceptance/layer-behavior-tests-test.js
This PR merges changes that remove the sidewalk cafes layer to coincide with the implementation of the City's new outdoor dining policies.
> Merging removal of sidewalk cafes layer for prod release

- app/components/layer-record-views/tax-lot.js
- app/components/main-map.js
- app/components/map-resource-search.js
- app/components/mapbox/map-feature-renderer.js
- app/controllers/map-feature.js
- app/layers/comparison-selected-lot.js
- app/models/lot-comparison.js
- app/router.js
- app/routes/application.js
- app/routes/index.js
- app/routes/map-feature/lot-comparison.js
- app/services/main-map.js
- app/styles/layouts/_l-default.scss
- app/templates/components/layer-record-views/tax-lot.hbs
- app/templates/components/main-map.hbs
- app/templates/map-feature.hbs
- app/templates/map-feature/lot-comparison.hbs
- app/utils/bbl-demux.js
- config/environment.js
- config/icons.js
This PR allows users to select 2 lots to compare them.
Completes #1190
> Dh8 multilot

- app/controllers/application.js
- config/environment.js
Updated environment and application js to update default checked CCD from 2013-2023 to 2024-2033
Closes #1209
> Issue/1209 Change Default Checked CCD

- app/controllers/application.js
- config/environment.js
Merges changes from #1210 to master for prod release
> Default to 2024-2033 city council districts

- app/controllers/application.js
- config/environment.js
Merging changes from #1213  up to master.
> Merge change for new Bronx special district to master

- app/components/layer-record-views/tax-lot/intersecting-layers-views.js
- app/templates/components/layer-palette.hbs
- app/templates/components/layer-record-views/tax-lot/intersecting-layers-views.hbs
- config/environment.js
- mirage/static-fixtures/layer-groups.js
- package.json
- public/layer-groups.json
- tests/acceptance/layer-behavior-tests-test.js
- yarn.lock
- Move transit layer to appendix I
- Add greater Transit Zone
- Add parking geographies
closes #1215
> City of Yes for Housing Opportunity

- mirage/static-fixtures/layer-groups.js
> Issue 1219 Updated Asset Link in ZOLA

- app/templates/components/layer-record-views/tax-lot/intersecting-layers-views.hbs
> Issue 1222 Updated Web Link

- app/components/layer-record-views/tax-lot.js
Update digital tax map hyperlinks to point to digital ocean spaces
closes #1221
> Digital ocean tax maps

- app/components/layer-record-views/tax-lot.js
- app/templates/components/layer-record-views/tax-lot/intersecting-layers-views.hbs
- mirage/static-fixtures/layer-groups.js
develop -> master
- tax map, asset, site hyperlinks for DCP home page update
> Release hyperlinks

- app/components/layer-record-views/tax-lot.js
Add leading zero to zoning map path
closes #1221
> Bugfix: incorrect zoning map path

- app/components/layer-record-views/tax-lot.js
feature branch -> master
Add leading zero to maps labeled with single digit
> Release: Bugfix: incorrect zoning map path

- app/components/bookmarks/types/zoning-map-index.js
- app/components/main-map.js
- app/models/zoning-map-index.js
- app/routes/map-feature/zoning-map-index.js
- app/templates/components/bookmarks/types/-default.hbs
- app/templates/components/layer-palette.hbs
- app/templates/map-feature/zoning-map-index.hbs
Updated `main-map.js` to look for and use `zmi_id` to open information detail side panel.
Enabled `selected` css highlighting and bookmarks
Closes #1242
> Issue 1242 Enabled Clickable Zoning Index Map Grid Squares

- app/components/default-modal.js
- app/templates/components/slideshow-contents.hbs
- app/templates/features.hbs
This PR added the Zoning Map Index to new features modal and features page.
Closes #1251
> 1251 Add Zoning Map Index copy and GIF to Zola New Features pop-up

- app/templates/features.hbs
This PR updates the "Features" panel to show the Zoning Map Index under "Features" in addition to where it is already listed under "New Features".
> Add Zoning Map Index to Features section
